### PR TITLE
Alpine Linux

### PR DESCRIPTION
**Pull request by DeviaVir**
Uses a way smaller footprint, so when grabbing this codebase on boot for some instances, the smaller the better.

Our use-cases are still supported:

```
~ docker run -e REGION=us-west-2 docker-aws-cli sh -c 'echo $REGION'
us-west-2
```

```
~ docker run docker-aws-cli sh -c 'aws cli'
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument command: Invalid choice, valid choices are:

acm                                      | apigateway
autoscaling                              | cloudformation
cloudfront                               | cloudhsm
cloudsearch                              | cloudsearchdomain
cloudtrail                               | cloudwatch
codecommit                               | codepipeline
cognito-identity                         | cognito-idp
cognito-sync                             | datapipeline
devicefarm                               | directconnect
dms                                      | ds
dynamodb                                 | dynamodbstreams
ec2                                      | ecr
ecs                                      | efs
elasticache                              | elasticbeanstalk
elastictranscoder                        | elb
emr                                      | es
events                                   | firehose
gamelift                                 | glacier
iam                                      | importexport
inspector                                | iot
iot-data                                 | kinesis
kms                                      | lambda
logs                                     | machinelearning
marketplacecommerceanalytics             | meteringmarketplace
opsworks                                 | rds
redshift                                 | route53
route53domains                           | sdb
ses                                      | sns
sqs                                      | ssm
storagegateway                           | sts
support                                  | swf
waf                                      | workspaces
s3api                                    | s3
configure                                | deploy
configservice                            | help
```

@pebble/webops

### CODE REVIEW

**Comment by thepwagner** [comment]
https://hub.docker.com/r/pebbletech/docker-aws-cli/tags/ says this brews a 76MB image

https://github.com/mycloudandme/docker-awscli -> https://hub.docker.com/r/pwagner/awscli/tags/ brews a 26MB image (and I include `jq` as cruft (build server requirement@localhost))

+1, but I think we can go thinner.

**Comment by DeviaVir** [comment]
@thepwagner nice, 24MB (vs >270MB) now!
https://hub.docker.com/r/pebbletech/docker-aws-cli/tags/

**Comment by thepwagner** [comment]
+1

**Comment by lrvick** [comment]
+1

**Pull request merged**
